### PR TITLE
Accept hash from Hiera to build an additional InclExcl.hash

### LINKED ISSUE #16: add inclexcl.hiera hash (like config_hash) so we can manage inclexcl entries via hiera

### PR DESCRIPTION
**Pull request by GerbenWelter**
Accept hash from Hiera to build an additional InclExcl.hash file to give the user more flexibility in setting the includes and excludes for TSM to use.

This PR builds on the work of @bschonec and will hopefully fix the outstanding issues @tosmi had with #46 .

This PR will add an optional extra INCLExcl line to the dsm.sys to source the InclExcl.hash file. I decided to always create this file even if the hash is empty otherwise it might conflict with dsm.sys when $::tsm::config_replace is set to 'false'.

Fixes #16 and #47

### CODE REVIEW

**Comment by GerbenWelter** [comment]
@tosmi The CI errors seem to come from the metadata.json. Do you mind if I leave that up to you fix?

**Comment by tosmi** [comment]
ok, thanks i'll look into this. sorry for the delay but i'm currently quite busy...

**Comment by GerbenWelter** [comment]
@tosmi Do you have a chance to review this any time soon?

**Comment by tosmi** [comment]
sorry for the delay. i'll work on a new release today, let's see how far this goes. would it be possible to implement some rudimentary tests for this?

**Pull request merged**
